import { Icons } from "@/components/icons";

export const techStack: {
    name: string;
    key: string;
    icon?: React.ElementType;
}[] = [
    { name: "HTML", key: "html", icon: Icons.html },
    { name: "CSS", key: "css", icon: Icons.css },
    { name: "JavaScript", key: "js", icon: Icons.js },
    { name: "React", key: "react", icon: Icons.react },
    { name: "React Router", key: "reactRouter", icon: Icons.reactRouter },
    { name: "Axios", key: "axios", icon: Icons.axios },
    { name: "Zustand", key: "zustand", icon: Icons.zustand },
    { name: "Redux", key: "redux", icon: Icons.redux },
    { name: "Redux Toolkit", key: "reduxToolkit", icon: Icons.redux },
    {name: "Tanstack Query", key: "tanstackQuery", icon: Icons.tanstackQuery},
    { name: "Next.js", key: "nextjs", icon: Icons.nextjs },
    { name: "Go", key: "go", icon: Icons.go },
    { name: "Tailwind CSS", key: "tailwind", icon: Icons.tailwind },
    { name: "Bootstrap CSS", key: "bootstrap", icon: Icons.bootstrap },
    { name: "TypeScript", key: "ts", icon: Icons.ts },
    { name: "MongoDB", key: "mongo", icon: Icons.mongo },
    { name: "Shadcn UI", key: "shadcnui", icon: Icons.shadcnui },
    { name: "PostgreSQL", key: "pg", icon: Icons.pg },
    { name: "MDX", key: "mdx", icon: Icons.mdx },
    { name: "Prisma", key: "prisma", icon: Icons.prisma },
    { name: "Express.js", key: "expressjs", icon: Icons.expressjs },
    { name: "NestJS", key: "nestjs", icon: Icons.nestjs },
    { name: "Java", key: "java", icon: Icons.java },
    { name: "Spring Boot", key: "springboot", icon: Icons.springboot },
    { name: "Hibernate", key: "hibernate", icon: Icons.hibernate },
    { name: "Mockito", key: "mockito", icon: Icons.junit },
    { name: "JUnit", key: "junit", icon: Icons.junit },
    { name: "Thymeleaf", key: "thymeleaf", icon: Icons.thymeleaf },
    { name: "Jenkins", key: "jenkins", icon: Icons.jenkins },
    { name: "Vite", key: "vite", icon: Icons.vite },
    { name: "Formik", key: "formik", icon: Icons.formik },
    { name: "Jest", key: "jest", icon: Icons.jest },
    { name: "GitHub Actions", key: "githubactions", icon: Icons.githubactions },
    { name: "Payload CMS", key: "payload", icon: Icons.payload },
    { name: "Node.js", key: "nodejs", icon: Icons.nodejs },
    { name: "Zod", key: "zod", icon: Icons.zod },
    { name: "Docker", key: "docker", icon: Icons.docker },
    { name: "LangGraph", key: "langgraph", icon: Icons.langgraph },
    { name: "Nginx", key: "nginx", icon: Icons.nginx },
    { name: "React Testing Library", key: "reacttestinglibrary", icon: Icons.reacttestinglibrary },
    { name: "better-auth", key: "betterauth", icon: Icons.betterauth },
    { name: "Yup", key: "yup" },
];
